name: Tosch Photography
favicon: null
layout_spectrum: 0.5964324488304555
typography_spectrum: 0.6337310855742544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27854815078899264
  lightness: 0.8273133409675211
  saturation: 0.3492997733410448
  rhythmicContrast: 0.7874822553712875
purpose: []
